### PR TITLE
[feat][refactor] Create Typography Documentation

### PR DESCRIPTION
**Pull request by Hamdrive**
Created Typography documentation
In addition, I have refactored existing CSS files to relocate all typography related stylings to one central CSS file
typography

### CODE REVIEW

**Review by stutisk — COMMENTED** [review]
this code looks great!

**Review by AnuragSahu11 — COMMENTED** [review]
Nicely done, you have made good typography classes

**Review by MaruthiPothuganti — COMMENTED** [review]
The code looks Clean and deign looks pretty awesome too..

**Comment by Hamdrive** [comment]
Merge to dev branch

**Pull request merged**
