### PR TITLE
[feat] Rating component

### PR DESCRIPTION
**Pull request by Hamdrive**
Created a new component, ratings
Primarily aimed to use in Ecommerce or other websites where user opinions can be easily expressed as a rating 
Icons used are imported from FontAwesome

Majority of HTML files are just sidebar updates and can be skimmed for quick review.

Deployed here : [Rating component](https://deploy-preview-36--powertrain-ui.netlify.app/documentation/html/rating.html)

image

### CODE REVIEW

**Review by hinanshisuthar — APPROVED** [review]
Amazing work done, Hamza. This is ready to merge!

**Review by ZuberDunge — APPROVED** [review]
Good code structure, easily readable. Everything looks perfect. Good to go from my side

**Review by abhij1607 — APPROVED** [review]
Very clean code! Used good practices
Goog to merge

**Comment by Hamdrive** [comment]
Successfully reviewed component, merging to dev and closing branch

**Pull request merged**
