### PR TITLE
Merge Image Component

### PR DESCRIPTION
**Pull request by Hamdrive**
Created 4 types of images:
1. Square image
2. Round image
3. Round corner image
4. Dynamic image

Image

### CODE REVIEW

**Review by FarhanMobashir — APPROVED** [review]
All good ✅

**Review by ritik-patel05 — COMMENTED** [review]
Better naming?
Attaching `-img` to all classes at suffix?

Otherwise, looks good to me!

**Review by maitrakhatri — APPROVED** [review]
looks good

**Comment by Hamdrive** [comment]
Suggested changes made. Merging to dev

**Pull request merged**
